[workspace]
member = ["mcpp_core", "evalater_gui"]
members = [ "evalater_gui","mcpp_core"]

[workspace.package]
version = "0.0.1"
authors = ["Kinokov Shotaskovich"]
description = "Integrated crafttable of MC++ ecosystem"
