[package]
name = "evalater_gui"
edition = "2024"
version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
clipboard = "0.5.0"
eframe = "0.31.1"
egui = "0.31.1"
mcpp_core = { path = "../mcpp_core" }
